# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'netflixUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for netflixUIKit

  # AI
  # pod 'Firebase/MLVisionLabelModel
  # pod 'FirebaseMLModelDownloader'
  # Network
  pod 'Alamofire'
  pod 'netfox'

  # Image
  pod 'Kingfisher'
  pod 'StepSlider'
  #pod 'FirebaseStorage'

  # Placeholder
  pod 'SkeletonView'
  
  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # LogInWithGoogle
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  #, '>= 9.6.0'
  #pod 'GoogleSignIn'

  # Animation
  pod 'Hero'
  pod 'lottie-ios'
  #pod "ViewAnimator"
  
  # View
  pod 'Parchment'
  #pod 'SnapKit'
  #pod 'FloatingPanel'

  # KeyboardManagement
  pod 'IQKeyboardManagerSwift'

  # Temp
  pod 'GoogleSignIn'
  #, '7.0.0'
  pod 'FirebaseStorage'
  #, '10.18.0'
#  pod 'GoogleMLKit/TextRecognition', '>= 0.6.0'
  
  
end
