# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'netflixUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for netflixUIKit
  
  # Network
  pod 'Alamofire'
  pod 'netfox'

  # Image
  pod 'Kingfisher'

  # Voice
  pod 'InstantSearchVoiceOverlay'

  # Placeholder
  pod 'SkeletonView'
  
  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Google
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'FirebaseStorage'
  pod 'Google-Mobile-Ads-SDK'

  # Animation
  pod 'Hero'
  pod 'lottie-ios'
  
  # View
  pod 'Parchment'
  pod 'youtube-ios-player-helper'
  #pod 'SnapKit'

  # KeyboardManagement
  pod 'IQKeyboardManagerSwift'
    
  # Language
  pod 'LanguageManager-iOS'
end
