# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'netflixUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for netflixUIKit

  # Network
  pod 'Alamofire'
  pod 'netfox'

  # Image
  pod 'Kingfisher'
  pod 'StepSlider'
  
  # Placeholder
  pod 'SkeletonView'
  
  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # LogInWithGoogle
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  # Animation
  pod "ViewAnimator"
  pod 'lottie-ios'
  
  # View
  #pod 'SnapKit'
  #pod 'FloatingPanel'

  # KeyboardManagement
  pod 'IQKeyboardManagerSwift'

end
